2024-03-28T17:09:52.448 | ERROR | [ejemplo_2_logging.py] | [26] | Mqtt Local connection faild
2024-03-28T17:13:55.581 | ERROR | [ejemplo_2_logging.py] | [26] | Mqtt Local connection faild
